//Types for Sign up objects
export const SIGNUP_OBJ_SUCCESS = 'SIGNUP_OBJ_SUCCESS';
export const SIGNUP_OBJ_CLEAR = 'SIGNUP_OBJ_CLEAR';

//Types for Login
export const LOGIN_REQUEST_REQUEST = 'LOGIN_REQUEST_REQUEST';
export const LOGIN_REQUEST_SUCCESS = 'LOGIN_REQUEST_SUCCESS';
export const LOGIN_REQUEST_FAILURE = 'LOGIN_REQUEST_FAILURE';

export const UPDATE_AUTH_TYPE_SUCCESS = 'UPDATE_AUTH_TYPE_SUCCESS';

//Types for Logout
export const LOGOUT_REQUEST_REQUEST = 'LOGOUT_REQUEST_REQUEST';
export const LOGOUT_REQUEST_SUCCESS = 'LOGOUT_REQUEST_SUCCESS';
export const LOGOUT_REQUEST_FAILURE = 'LOGOUT_REQUEST_FAILURE';

//Types for Validate token
export const VALIDATE_TOKEN_REQUEST = 'VALIDATE_TOKEN_REQUEST';
export const VALIDATE_TOKEN_SUCCESS = 'VALIDATE_TOKEN_SUCCESS';
export const VALIDATE_TOKEN_FAILURE = 'VALIDATE_TOKEN_FAILURE';

//Types for Sign up
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

//Types for Save User Info
export const FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAILURE = 'FORGOT_PASSWORD_FAILURE';

//Types for Get apple User
export const GET_APPLE_USER_REQUEST = 'GET_APPLE_USER_REQUEST';
export const GET_APPLE_USER_SUCCESS = 'GET_APPLE_USER_SUCCESS';
export const GET_APPLE_USER_FAILURE = 'GET_APPLE_USER_FAILURE';

//Types for Get apple User
export const SET_APPLE_USER_REQUEST = 'SET_APPLE_USER_REQUEST';
// export const SET_APPLE_USER_SUCCESS = 'GET_APPLE_USER_SUCCESS';
// export const SET_APPLE_USER_FAILURE = 'GET_APPLE_USER_FAILURE';

//Types of social login
export const SOCIAL_GOOGLE_REQUEST = 'SOCIAL_GOOGLE_REQUEST';
export const SOCIAL_GOOGLE_SUCCESS = 'SOCIAL_GOOGLE_SUCCESS';
export const SOCIAL_GOOGLE_FAILURE = 'SOCIAL_GOOGLE_FAILURE';

//Types of social login
export const SOCIAL_FACEBOOK_REQUEST = 'SOCIAL_FACEBOOK_REQUEST';
export const SOCIAL_FACBOOK_SUCCESS = 'SOCIAL_FACBOOK_SUCCESS';
export const SOCIAL_FACEBOOK_FAILURE = 'SOCIAL_FACEBOOK_FAILURE';

//Types of social login
export const SOCIAL_APPLE_REQUEST = 'SOCIAL_APPLE_REQUEST';
export const SOCIAL_APPLE_SUCCESS = 'SOCIAL_APPLE_SUCCESS';
export const SOCIAL_APPLE_FAILURE = 'SOCIAL_APPLE_FAILURE';

//Type for Drawer actions
export const SET_INITIAL_ROUTE = 'SET_INITIAL_ROUTE';

//Types of get categories
export const GET_CATEGORIES_REQUEST = 'GET_CATEGORIES_REQUEST';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_FAILURE = 'GET_CATEGORIES_FAILURE';

//Types of get services
export const GET_SERVICES_REQUEST = 'GET_SERVICES_REQUEST';
export const GET_SERVICES_SUCCESS = 'GET_SERVICES_SUCCESS';
export const GET_SERVICES_FAILURE = 'GET_SERVICES_FAILURE';

//Types of get services
export const LOAD_MORE_SERVICES_SUCCESS = 'LOAD_MORE_SERVICES_SUCCESS';

//Types of update categories
export const UPDATE_CATEGORY_REQUEST = 'UPDATE_CATEGORY_REQUEST';
export const UPDATE_CATEGORY_SUCCESS = 'UPDATE_CATEGORY_SUCCESS';

//Types of get post detail
export const SERVICE_DETAIL_REQUEST = 'SERVICE_DETAIL_REQUEST';
export const SERVICE_DETAIL_SUCCESS = 'SERVICE_DETAIL_SUCCESS';
export const SERVICE_DETAIL_FAILURE = 'SERVICE_DETAIL_FAILURE';

//Types of add to wishlist
export const ADD_TO_WISHLIST_REQUEST = 'ADD_TO_WISHLIST_REQUEST';
export const ADD_TO_WISHLIST_SUCCESS = 'ADD_TO_WISHLIST_SUCCESS';
export const ADD_TO_WISHLIST_FAILURE = 'ADD_TO_WISHLIST_FAILURE';

//Types of remove to Wishlist
export const REMOVE_FROM_WISHLIST_REQUEST = 'REMOVE_FROM_WISHLIST_REQUEST';
export const REMOVE_FROM_WISHLIST_SUCCESS = 'REMOVE_FROM_WISHLIST_SUCCESS';
export const REMOVE_FROM_WISHLIST_FAILURE = 'REMOVE_FROM_WISHLIST_FAILURE';

//Types of get the Wishlist
export const GET_WISHLIST_REQUEST = 'GET_WISHLIST_REQUEST';
export const GET_WISHLIST_SUCCESS = 'GET_WISHLIST_SUCCESS';
export const GET_WISHLIST_FAILURE = 'GET_WISHLIST_FAILURE';

//Types of get the Wishlist
export const WISHLIST_COUNT_REQUEST = 'WISHLIST_COUNT_REQUEST';
export const WISHLIST_COUNT_SUCCESS = 'WISHLIST_COUNT_SUCCESS';
export const WISHLIST_COUNT_FAILURE = 'WISHLIST_COUNT_FAILURE';

//Types of post a review
export const ADD_REVIEW_REQUEST = 'ADD_REVIEW_REQUEST';
export const ADD_REVIEW_SUCCESS = 'ADD_REVIEW_SUCCESS';
export const ADD_REVIEW_FAILURE = 'ADD_REVIEW_FAILURE';

//Types of search
export const SEARCH_REQUEST = 'SEARCH_REQUEST';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const LOAD_MORE_SEARCH_SUCCESS = 'LOAD_MORE_SEARCH_SUCCESS';
export const SEARCH_FAILURE = 'SEARCH_FAILURE';

//Types of filter
export const FILTER_REQUEST = 'FILTER_REQUEST';
export const FILTER_SUCCESS = 'FILTER_SUCCESS';
export const FILTER_FAILURE = 'FILTER_FAILURE';

//Types of GridView
export const SET_GRID_VIEW = 'SET_GRID_VIEW';

//Types of get profile
export const GET_PROFILE_REQUEST = 'GET_PROFILE_REQUEST';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_FAILURE = 'GET_PROFILE_FAILURE';

//Types of edit proifle
export const EDIT_PROFILE_REQUEST = 'EDIT_PROFILE_REQUEST';
export const EDIT_PROFILE_SUCCESS = 'EDIT_PROFILE_SUCCESS';
export const EDIT_PROFILE_FAILURE = 'EDIT_PROFILE_FAILURE';

//Types of get user packges
export const USER_PACKAGES_REQUEST = 'USER_PACKAGES_REQUEST';
export const USER_PACKAGES_SUCCESS = 'USER_PACKAGES_SUCCESS';
export const USER_PACKAGES_FAILURE = 'USER_PACKAGES_FAILURE';

//Types of get all packges
export const GET_PACKAGES_REQUEST = 'GET_PACKAGES_REQUEST';
export const GET_PACKAGES_SUCCESS = 'GET_PACKAGES_SUCCESS';
export const GET_PACKAGES_FAILURE = 'GET_PACKAGES_FAILURE';

//Types of saving user search
export const SAVE_SEARCH_REQUEST = 'SAVE_SEARCH_REQUEST';
export const SAVE_SEARCH_SUCCESS = 'SAVE_SEARCH_SUCCESS';
export const SAVE_SEARCH_FAILURE = 'SAVE_SEARCH_FAILURE';

//Types of saving sorting filter search
export const SORT_FILTER_REQUEST = 'SORT_FILTER_REQUEST';
export const SORT_FILTER_SUCCESS = 'SORT_FILTER_SUCCESS';
export const SORT_FILTER_FAILURE = 'SORT_FILTER_FAILURE';

//Types of saving user search
export const GET_SAVED_SEARCHES_REQUEST = 'GET_SAVED_SEARCHES_REQUEST';
export const GET_SAVED_SEARCHES_SUCCESS = 'GET_SAVED_SEARCHES_SUCCESS';
export const GET_SAVED_SEARCHES_FAILURE = 'GET_SAVED_SEARCHES_FAILURE';

//Types of saving user search
export const REMOVE_SAVE_SEARCH_REQUEST = 'REMOVE_SAVE_SEARCH_REQUEST';
export const REMOVE_SAVE_SEARCH_SUCCESS = 'REMOVE_SAVE_SEARCH_SUCCESS';
export const REMOVE_SAVE_SEARCH_FAILURE = 'REMOVE_SAVE_SEARCH_FAILURE';

export const SORT_SELECT_ALRET = 'SORT_SELECT_ALRET';

//Types of Add Listing
export const ADD_LISTING_REQUEST = 'ADD_LISTING_REQUEST';
export const ADD_LISTING_SUCCESS = 'ADD_LISTING_SUCCESS';
export const ADD_LISTING_FAILURE = 'ADD_LISTING_FAILURE';

//Types of Add Listing
export const EDIT_LISTING_REQUEST = 'EDIT_LISTING_REQUEST';
export const EDIT_LISTING_SUCCESS = 'EDIT_LISTING_SUCCESS';
export const EDIT_LISTING_FAILURE = 'EDIT_LISTING_FAILURE';

//Types of Add Listing
export const DELETE_LISTING_REQUEST = 'DELETE_LISTING_REQUEST';
export const DELETE_LISTING_SUCCESS = 'DELETE_LISTING_SUCCESS';
export const DELETE_LISTING_FAILURE = 'DELETE_LISTING_FAILURE';

//Types of Add Listing
export const GET_LISTING_REQUEST = 'GET_LISTING_REQUEST';
export const GET_LISTING_SUCCESS = 'GET_LISTING_SUCCESS';
export const GET_LISTING_FAILURE = 'GET_LISTING_FAILURE';

//Types of Add Listing Data
export const GET_ADDLISTING_DATA_REQUEST = 'GET_ADDLISTING_DATA_REQUEST';
export const GET_ADDLISTING_DATA_SUCCESS = 'GET_ADDLISTING_DATA_SUCCESS';
export const GET_ADDLISTING_DATA_FAILURE = 'GET_ADDLISTING_DATA_FAILURE';

//Types of clear listing form
export const CLEAR_ADD_LISTING_FORM = 'CLEAR_ADD_LISTING_FORM';

//Types of clear listing form
export const ADD_IN_WEEKTIME = 'ADD_TIME_WEEKTIME';
export const REMOVE_IN_WEEKTIME = 'REMOVE_TIME_WEEKTIME';
export const CLEAR_WEEKTIMES = 'CLEAR_WEEKTIMES';

//Types of clear additional form
export const ADD_IN_ADDITIONAL = 'ADD_IN_ADDITIONAL';
export const REMOVE_FROM_ADDITIONAL = 'REMOVE_FROM_ADDITIONAL';
export const CLEAR_ADDITIONAL = 'CLEAR_ADDITIONAL';

//Cart
export const ADD_TO_CART_REQUEST = 'ADD_TO_CART_REQUEST';
export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS';
export const ADD_TO_CART_FAILURE = 'ADD_TO_CART_FAILURE';

export const REMOVE_FROM_CART_REQUEST = 'REMOVE_FROM_CART_REQUEST';
export const REMOVE_FROM_CART_SUCCESS = 'REMOVE_FROM_CART_SUCCESS';
export const REMOVE_FROM_CART_FAILURE = 'REMOVE_FROM_CART_FAILURE';

export const GET_CART_REQUEST = 'GET_CART_REQUEST';
export const GET_CART_SUCCESS = 'GET_CART_SUCCESS';
export const GET_CART_FAILURE = 'GET_CART_FAILURE';

export const GET_ORDERS_REQUEST = 'GET_ORDERS_REQUEST';
export const GET_ORDERS_SUCCESS = 'GET_ORDERS_SUCCESS';
export const GET_ORDERS_FAILURE = 'GET_ORDERS_FAILURE';

export const ORDER_DETAIL_REQUEST = 'ORDER_DETAIL_REQUEST';
export const ORDER_DETAIL_SUCCESS = 'ORDER_DETAIL_SUCCESS';
export const ORDER_DETAIL_FAILURE = 'ORDER_DETAIL_FAILURE';

export const PAYMENT_GETEWAYS_REQUEST = 'PAYMENT_GETEWAYS_REQUEST';
export const PAYMENT_GETEWAYS_SUCCESS = 'PAYMENT_GETEWAYS_SUCCESS';
export const PAYMENT_GETEWAYS_FAILURE = 'PAYMENT_GETEWAYS_FAILURE';

export const ADD_PAYMENT_GATEWAY_REQUEST = 'ADD_PAYMENT_GATEWAY_REQUEST';
export const ADD_PAYMENT_GATEWAY_SUCCESS = 'ADD_PAYMENT_GATEWAY_SUCCESS';
export const ADD_PAYMENT_GATEWAY_FAILURE = 'ADD_PAYMENT_GATEWAY_FAILURE';

export const DELETE_PAYMENT_GATEWAY_REQUEST = 'DELETE_PAYMENT_GATEWAY_REQUEST';
export const DELETE_PAYMENT_GATEWAY_SUCCESS = 'DELETE_PAYMENT_GATEWAY_SUCCESS';
export const DELETE_PAYMENT_GATEWAY_FAILURE = 'DELETE_PAYMENT_GATEWAY_FAILURE';

export const GET_CLAIMED_REQUEST = 'GET_CLAIMED_REQUEST';
export const GET_CLAIMED_SUCCESS = 'GET_CLAIMED_SUCCESS';
export const GET_CLAIMED_FAILURE = 'GET_CLAIMED_FAILURE';

export const GET_REPORTED_REQUEST = 'GET_REPORTED_REQUEST';
export const GET_REPORTED_SUCCESS = 'GET_REPORTED_SUCCESS';
export const GET_REPORTED_FAILURE = 'GET_REPORTED_FAILURE';

export const GET_ADDRESSES_REQUEST = 'GET_ADDRESSES_REQUEST';
export const GET_ADDRESSES_SUCCESS = 'GET_ADDRESSES_SUCCESS';
export const GET_ADDRESSES_FAILURE = 'GET_ADDRESSES_FAILURE';

export const EDIT_ADDRESS_REQUEST = 'EDIT_ADDRESS_REQUEST';
export const EDIT_ADDRESS_SUCCESS = 'EDIT_ADDRESS_SUCCESS';
export const EDIT_ADDRESS_FAILURE = 'EDIT_ADDRESS_FAILURE';

export const GET_CARDS_REQUEST = 'GET_CARDS_REQUEST';
export const GET_CARDS_SUCCESS = 'GET_CARDS_SUCCESS';
export const GET_CARDS_FAILURE = 'GET_CARDS_FAILURE';

export const ADD_CARD_REQUEST = 'ADD_CARD_REQUEST';
export const ADD_CARD_SUCCESS = 'ADD_CARD_SUCCESS';
export const ADD_CARD_FAILURE = 'ADD_CARD_FAILURE';

export const APPLY_COUPEN_REQUEST = 'APPLY_COUPEN_REQUEST';
export const APPLY_COUPEN_SUCCESS = 'APPLY_COUPEN_SUCCESS';
export const APPLY_COUPEN_FAILURE = 'APPLY_COUPEN_FAILURE';

export const CHECKOUT_NONCE_REQUEST = 'CHECKOUT_NONCE_REQUEST';
export const CHECKOUT_NONCE_SUCCESS = 'CHECKOUT_NONCE_SUCCESS';
export const CHECKOUT_NONCE_FAILURE = 'CHECKOUT_NONCE_FAILURE';

export const PLACE_ORDER_REQUEST = 'PLACE_ORDER_REQUEST';
export const PLACE_ORDER_SUCCESS = 'PLACE_ORDER_SUCCESS';
export const PLACE_ORDER_FAILURE = 'PLACE_ORDER_FAILURE';

export const VALIDATE_PACKAGE_REQUEST = 'VALIDATE_PACKAGE_REQUEST';
export const VALIDATE_PACKAGE_SUCCESS = 'VALIDATE_PACKAGE_SUCCESS';
export const VALIDATE_PACKAGE_FAILURE = 'VALIDATE_PACKAGE_FAILURE';

export const SET_ACTIVE_TAB = 'SET_ACTIVE_TAB';

export const IS_CONTENT_SCROLLING = 'IS_CONTENT_SCROLLING';

export const RANDOM_POST_REQUEST = 'RANDOM_POST_REQUEST';
export const RANDOM_POST_SUCCESS = 'RANDOM_POST_SUCCESS';
export const RANDOM_POST_FAILURE = 'RANDOM_POST_FAILURE';
